# The Product Value Model defines the value your product delivers to users.
# It is tech-agnostic and should be built from scratch for your specific product.
# Its structure (Layers, Components, Sub-components) forms the sections of your living Product Requirement Document (PRD).
#
# CRITICAL: This is a BRIDGE DOCUMENT serving two audiences:
# 1. Business Stakeholders (investors, executives, BD, regulators) - must understand value without technical knowledge
# 2. Engineering Teams (developers, architects, DevOps) - need implementation context
#
# LANGUAGE RULES:
# - Component names & UVPs: BUSINESS LANGUAGE ONLY (what value, who benefits)
# - Context tags: Technical details prefixed with "Technical:" for engineering team
# - NEVER use: protocols (FIX, GraphQL, REST), DevOps patterns (Blue-Green, CI/CD), acronyms (API, DB, MLOps)
# - See docs/guides/VALUE_MODEL_BUSINESS_LANGUAGE_GUIDE.md for complete guidance
#
track_name: "Product"
version: "1.0.0"
status: "placeholder"
description: "This is a placeholder for the Product Value Model. It should be developed from scratch for your specific product."
high_level_model:
  product_mission: ""
  main_goal: ""
  product_goals: []
  value_delivery_description: []
  needs_addressed: []
  values_delivered: []
  solution_steps: []
activation_notes: "This is a comprehensive map of potential value. Flip `active: true` on L3 sub-components as you decide to invest in them. Start narrow and focused."

# EXAMPLE STRUCTURE (delete and replace with your product):
# layers:
#   # Layer 1 & 2: User-Facing (focus on user experience and business outcomes)
#   - layer_number: 1
#     layer_name: InvestorApp
#     layer_description: "Mobile and web application for fund investors"
#     solution_steps:
#       - step: "Implement responsive design supporting mobile and web platforms"
#         outcome: "Investors can access portfolio information from any device, improving engagement"
#       - step: "Provide real-time data synchronization across all client platforms"
#         outcome: "Users see consistent information regardless of access point, building trust"
#       - step: "Enable push notifications for critical portfolio events"
#         outcome: "Investors receive timely alerts about important changes, improving decision speed"
#     components:
#       - component_name: PortfolioMonitoring
#         uvp: "Real-time portfolio performance is displayed so that investors can track returns, which helps us provide transparency and build trust."
#         # ✅ Good: Business outcome, clear beneficiary, no technical jargon
#         sub_components:
#           - name: PerformanceCharts
#             uvp: "Portfolio performance trends are visualized so that investors can understand growth patterns, which helps them make informed decisions."
#
#   # Layer 3: Service Layer (HIGH RISK for technical drift - focus on capabilities not protocols)
#   - layer_number: 3
#     layer_name: ApplicationHostingAPI
#     layer_description: "Backend services and data layer"
#     solution_steps:
#       - step: "Establish secure connections to European power exchanges"
#         outcome: "Fund can execute trades on major markets, expanding trading opportunities"
#       - step: "Implement real-time data feeds for market and position monitoring"
#         outcome: "Trading team has instant visibility into operations, enabling quick decisions"
#       - step: "Build robust error handling and retry logic for critical operations"
#         outcome: "System maintains reliability during market volatility, protecting capital"
#     components:
#       - component_name: ExchangeConnectivity  # ✅ Good: Business capability
#         # ❌ Bad: FIXAPIConnections (protocol name)
#         uvp: "Trade orders are executed reliably on European power exchanges so that fund managers can capture market opportunities, which helps us generate trading revenue."
#         # ✅ Good: Business outcome, clear beneficiary
#         # ❌ Bad: "Execute orders via FIX API to EEX" (protocol-focused)
#         context: "Technical: Implements FIX API protocol for EEX and EPEX exchanges via ABN AMRO Clearing. Includes retry logic, connection monitoring, and failover handling."
#         # ✅ Good: Technical details in context tag, prefixed with "Technical:"
#         sub_components:
#           - name: GermanMarketAccess  # ✅ Good: Business region
#             # ❌ Bad: EEXConnection (exchange acronym)
#             uvp: "German power market orders are executed so that fund can trade the largest European exchange, which helps us maximize liquidity."
#             context: "Technical: FIX 4.4 connection to EEX for spot and day-ahead futures."
#
#       - component_name: RealTimeOperationsInterface  # ✅ Good: Business function
#         # ❌ Bad: GraphQLAPI (protocol name)
#         uvp: "Trading operations data is accessible instantly so that staff can monitor and control algorithms effectively, which helps us respond quickly to market conditions."
#         # ✅ Good: Instant access outcome, clear beneficiary (staff)
#         # ❌ Bad: "GraphQL API for real-time queries" (protocol-focused)
#         context: "Technical: GraphQL API serving Staff App with real-time subscriptions. Implements authentication and role-based access control."
#         # ✅ Good: GraphQL mentioned in context, not main UVP
#
#   # Layer 4: Infrastructure/Operations (HIGHEST RISK - focus on outcomes not deployment patterns)
#   - layer_number: 4
#     layer_name: CloudSecurityOperations
#     layer_description: "Infrastructure, deployment, and operational support"
#     solution_steps:
#       - step: "Implement zero-downtime deployment strategy for platform updates"
#         outcome: "Trading operations continue uninterrupted during updates, meeting 99.9% SLA"
#       - step: "Deploy comprehensive monitoring and alerting infrastructure"
#         outcome: "Operations team detects issues instantly before customer impact"
#       - step: "Configure automated backup and disaster recovery procedures"
#         outcome: "Fund data remains protected even in catastrophic failure scenarios"
#     components:
#       - component_name: SafePlatformUpdates  # ✅ Good: Safety outcome
#         # ❌ Bad: BlueGreenDeployment (DevOps pattern)
#         uvp: "Platform updates are deployed without trading interruptions so that operations can continue reliably, which helps us maintain 99.9% uptime SLA."
#         # ✅ Good: Zero-downtime outcome, business SLA focus
#         # ❌ Bad: "Blue-green deployment runs new version in parallel" (pattern-focused)
#         context: "Technical: Blue-green deployment pattern with health checks and instant rollback. New version runs in parallel environment, traffic switches after validation."
#         # ✅ Good: Pattern details in context tag
#         sub_components:
#           - name: GradualAlgorithmRollouts  # ✅ Good: Validation outcome
#             # ❌ Bad: CanaryDeployment (DevOps pattern)
#             uvp: "Algorithm improvements are validated with limited capital before full deployment so that fund can avoid costly errors, which helps us protect investor capital."
#             # ✅ Good: Risk mitigation outcome, capital protection focus
#             # ❌ Bad: "Canary deployment tests on 5% live capital" (pattern-focused)
#             context: "Technical: Canary deployment strategy - new model version deployed to 5% of capital for 24-hour observation. Automatic rollback if performance degrades."
#
#           - name: ContinuousAlgorithmLearning  # ✅ Good: Learning outcome
#             # ❌ Bad: MLOpsPipeline (technical domain)
#             uvp: "Trading algorithms improve daily from market patterns without operational disruption so that performance remains competitive, which helps us maximize returns."
#             # ✅ Good: Continuous improvement outcome, competitive advantage focus
#             # ❌ Bad: "MLOps pipeline automates model retraining" (process-focused)
#             context: "Technical: MLOps pipeline retrains 6 expert models nightly using previous 90 days of data. Zero-downtime deployment via model versioning."
#
# VALIDATION CHECKLIST (run before committing):
# [ ] No protocols in names/UVPs (FIX, GraphQL, REST, WebSocket, HTTP)
# [ ] No DevOps patterns in names/UVPs (Blue-Green, Canary, CI/CD, MLOps)
# [ ] No technical acronyms in names/UVPs (API, DB, K8s, JSON, XML)
# [ ] All UVPs follow pattern: "{Deliverable} so that {beneficiary} can {capability}, which helps us {progress}"
# [ ] Technical details in context tags prefixed "Technical:"
# [ ] Can non-technical investor understand main content? (5-question test)

layers: []

